# 定义第一个训练 Pod（主节点）
apiVersion: v1  # 使用 Kubernetes 核心 API 版本 v1
kind: Pod       # 类型是 Pod
metadata:
  name: megatron-train-node-0  # Pod 名称（主节点）

spec:
  restartPolicy: Never         # 训练任务失败不自动重启
  hostNetwork: true            # 使用主机网络模式，方便节点间通信

  containers:
    - name: megatron           # 容器名称
      image: megatron-lm:v1    # 使用本地的 Megatron 镜像（已导入）
      imagePullPolicy: Never   # 不从远程拉取镜像（确保只用本地镜像）

      command: ["/bin/bash", "-c"]  # 使用 bash 运行命令
      args:
        - |
          cd /workspace/megatron-lm-custom && \
          bash pretrain_gpt_distributed_2node.sh  # 进入代码目录并运行训练脚本

      volumeMounts:
        - name: workspace        # 挂载主目录（代码、数据）
          mountPath: /workspace
        - name: dshm             # 挂载共享内存目录（避免 /dev/shm 空间不足）
          mountPath: /dev/shm

      resources:
        limits:
          nvidia.com/gpu: 2      # 限制容器使用 2 张 GPU
          ephemeral-storage: "10Gi"  # 临时存储上限
        requests:
          nvidia.com/gpu: 2      # 请求 2 张 GPU（调度器据此分配）
          ephemeral-storage: "1Gi"   # 临时存储最小申请值

      securityContext:
        privileged: true         # 启用特权模式，允许更多底层权限（用于挂载 /dev/shm）

  volumes:
    - name: workspace
      hostPath:
        path: /home/zhr          # 宿主机路径挂载为容器的 /workspace
        type: Directory
    - name: dshm
      emptyDir:
        medium: Memory           # 使用内存作为临时卷类型
        sizeLimit: 8Gi           # 限制为 8Gi 的共享内存（用于 /dev/shm）

  nodeSelector:
    kubernetes.io/hostname: dragonlab12-10-1  # 调度到指定节点（主节点）

---

# 定义第二个训练 Pod（从节点）
apiVersion: v1
kind: Pod
metadata:
  name: megatron-train-node-1  # Pod 名称（从节点）

spec:
  restartPolicy: Never
  hostNetwork: true

  containers:
    - name: megatron
      image: megatron-lm:v1
      imagePullPolicy: Never

      command: ["/bin/bash", "-c"]
      args:
        - |
          cd /workspace/megatron-lm-custom && \
          bash pretrain_gpt_distributed_2node.sh  # 同样运行从节点对应脚本

      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: dshm
          mountPath: /dev/shm

      resources:
        limits:
          nvidia.com/gpu: 2
          ephemeral-storage: "10Gi"
        requests:
          nvidia.com/gpu: 2
          ephemeral-storage: "1Gi"

      securityContext:
        privileged: true

  volumes:
    - name: workspace
      hostPath:
        path: /home/zhr
        type: Directory
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi

  nodeSelector:
    kubernetes.io/hostname: dragonlab12-11-1  # 调度到另一个节点
